### ISSUE TITLE
Status Code 500 beim  Rabattposition erfassen zu Rechnung

### ISSUE THREAD

**Issue by BoldewynKratzefuss** [diegosteiner/heimv#233]
# Kontext
|Name|Info|
|:-|:-|
|Version HeimV | Unreleased ‘Version 23.5.1’ |
|Browser | Chrome Version 113.0.5672.94 (Offizieller Build) (64-Bit)|

# Beschreibung
Für eine vergangene Vermietung möchte ich auf der Rechnung eine Rabattposition erfassen. Da dies weder in der Rubrik ‘Tarife & Verbrauch’ möglich ist, noch auf der Seite ‘Rechnung hinzufügen’,  erstelle ich die Rechnung und bearbeite sie anschliessend. In der Bearbeitung verwende ich die Funktion ‘Rechnungsposition hinzufügen’ und fülle sie wie folgt aus 
'Art der Rechnungsposition': 'Rabatt; 'Ordnungsnummer': 99; 'Text': 'Rabatt wegen blabla'; 'Aufschlüsselung': '20%'; 'Betrag': 123.40

Nach dem Klick auf ‘Erstellen’ werde ich mit HTTP Statuscode 500 konfrontiert

# Gewünschtes Verhalten
Das gewünschte Verhalten wäre, dass ich die Rabattposition in Prozent eingeben kann und dies schon beim initialen Erfassen der Rechnung zur Verfügung stünde.

# Details
Per Mail am 19.05.2023

**Comment by diegosteiner** [comment]
Danke @BoldewynKratzefuss für den perfekten Report :)

Ich habe den zugrundeliegenden Fehler im [Release 23.5.2](https://github.com/diegosteiner/heimv/releases/tag/23.5.2) gefixt. Es handelt sich allerdings um ein unfertiges Feature, das mit Vorsicht zu gebrauchen ist. Es ist eine Überarbeitung des UIs der Rechnungen geplant, aber das wird noch eine Weile dauern, bis es wie gewünscht funktioniert. Bitte trotzdem testen, wenn es deployt ist.
