### ISSUE TITLE
Lizenz unklar

### ISSUE THREAD

**Issue by carlobeltrame** [diegosteiner/heimv#241]
Im README zuunterst steht AGPLv3, im LICENSE file steht MIT. Was gilt?

**Comment by diegosteiner** [comment]
Ich weiss es eben selbst nicht... tendiere grundsätzlich aber zur AGPLv3. Was denkst du wäre besser @carlobeltrame ?

**Comment by carlobeltrame** [comment]
Ich weiss es auch nicht so genau... Ich mache bei meinen privaten Projekten meist MIT, aber auch nur weil ich mich nicht vertieft mit den verschiedenen Lizenzen auseinandergesetzt habe. Für ein Produkt mit dem du auch Geld verdienst wäre vielleicht die AGPLv3 schon besser (falls sie überhaupt kompatibel mit deinem dual licensing ist...)
https://choosealicense.com/
