### ISSUE TITLE
Rechnung erstellt mit Zusatzpositionen. Versendet ohne Zusatzpositionen, offen aber mit

### ISSUE THREAD

**Issue by BoldewynKratzefuss** [diegosteiner/heimv#328]
* Mit den Mietern abgemachte Positionen zur Schadensbehebung habe ich in der Rechnung erfasst. (Rechnung bearbeiten, Rechnungsposition hinzufügen)
* Die Rechnung in PDF Ansicht enthält diese Positionen
* Ebenso die Rechnung bei den offenen Rechnungen
* An den  Mieter wurde aber eine Rechnung versendet ohne diese Positionen. Dies ist ersichtlich in der Buchung unter 'Benachrichtigungen'
Gibt ein ziemliches Puff mit der Buchhaltung :-)

Beispiele
* https://app.heimv.ch/pfadiheim-enzenbuehl/manage/bookings/7984b902-68b5-4333-93af-94e1954b46e7?locale=de
* https://app.heimv.ch/pfadiheim-enzenbuehl/manage/bookings/9417857c-9f51-4871-9df4-0800f3ab8822?locale=de

Danke für's Beheben und beste Pfadigrüsse
Markus Kolmos / Bär

**Comment by diegosteiner** [comment]
@BoldewynKratzefuss Danke für die Meldung, ich konnte den Fehler beheben, wird mit dem nächsten Release ausgeliefert.
