### ISSUE TITLE
Licenses do not match

### ISSUE THREAD

**Issue by carlobeltrame** [diegosteiner/heimv#41]
https://github.com/diegosteiner/heimv/blob/develop/LICENSE contains a GPL license, while README.md talks about the AGPL license.

The difference [[1]](http://www.gnu.org/licenses/why-affero-gpl.html) as far as I understand it is that AGPL is like the GPL, with the additional requirement that the source code of any modified versions of the software must also be published by whoever modified it.

**Comment by diegosteiner** [comment]
You are absolutely right. Changed it to AGPL. Thank you.
